'\" -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH ktorrent 1 2006-12-205 "" ""
.SH NAME
ktorrent \- BitTorrent client for TDE
.SH SYNOPSIS
'nh
.fi
.ad l
\fBktorrent\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[
\fB\fIQt-options\fB\fR
] [
\fB\fITDE-options\fB\fR
]
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
BitTorrent client for TDE.
.PP
KTorrent is a BitTorrent program for TDE. Its features include speed capping (both down and up), integrated searching, UDP tracker support, preview of certain file types (video and audio) and integration into the TDE Panel enabling background downloading.
.SH OPTIONS
All TDE and Qt
programs accept a some common command-line options. ktorrent has no
application-specific options.
.PP
.TP 
\*(T<\fB\-\-help\fR\*(T> 
Show help about options
.TP 
\*(T<\fB\-\-help\-qt\fR\*(T> 
Show Qt specific options
.TP 
\*(T<\fB\-\-help\-tde\fR\*(T> 
Show TDE specific options
.TP 
\*(T<\fB\-\-help\-all\fR\*(T> 
Show all options
.TP 
\*(T<\fB\-\-author\fR\*(T> 
Show author information
.TP 
\*(T<\fB\-v\fR\*(T>, \*(T<\fB\-\-version\fR\*(T> 
Show version information
.TP 
\*(T<\fB\-\-license\fR\*(T> 
Show license information
.TP 
\*(T<\fB\-\-\fR\*(T> 
Indicates end of options
.SH COPYRIGHT
This manual page was written by Anthony Mercatante
<\*(T<tonio@ubuntu.com\*(T>> for the
Debian system (but may be used by others).
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License,
Version 2 or any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public
License can be found in
\*(T<\fI/usr/share/common\-licenses/GPL\fR\*(T>.
